baseURL = 'https://coffeeknife.nekoweb.org/'
languageCode = 'en-us'
title = "coffeeknife@nekoweb.org:~$"

theme='robin-theme'

[menus]
  [[menus.main]]
    name='about'
    pageRef='/about'
    weight=10
  [[menus.main]]
    name='tech'
    pageRef='/tech'
    weight=20
  [[menus.main]]
    name='media'
    pageRef='/media'
    weight=30
  [[menus.main]]
    name='crafts'
    pageRef='/crafts'
    weight=40
  [[menus.main]]
    name='blog'
    pageRef='/blog'
    weight=50
  [[menus.main]]
    name='guestbook'
    pageRef='/guestbook'
    weight=60
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe=true

[[params.social]]
  key = 0
  name = "github"
  url = "https://github.com/coffeeknife"
  target = "_blank"
  icon = "fa-brands fa-github"
  aria = "GitHub Profile"

[[params.social]]
  key = 1
  name = "bluesky"
  url = "https://coffeeknife.bsky.social/"
  icon = "fa-brands fa-bluesky"
  target = "_blank"
  aria = "Bluesky Profile"

[[params.social]]
  key = 2
  name = "email"
  url = "mailto:coffeeknife@proton.me"
  icon = "fa-solid fa-envelope"
  aria = "Email Address"

[[params.social]]
  key = 3
  name = "matrix"
  url = "matrix:@coffeeknife:matrix.org"
  icon = "fa-solid fa-comment"
  aria = "Matrix Account"