baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

assetDir = 'assets'

[params]
nowPlaying = 'p6snD1650ck' # youtube video id
display_posts = true

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"